In [ ]:
import pandas as pd

In [ ]:
df = pd.read_csv('Global Superstore.csv')
revenue = df['Sales'].sum()
profit = df['Profit'].sum()
orders = df['Order ID'].nunique()
customers = df['Customer ID'].nunique()

avg_order_value = revenue / orders
avg_order_profit = profit / orders

print("Revenue:", round(revenue, 2))
print("Profit:", round(profit, 2))
print("Orders:", orders)
print("Customers:", customers)
print("Average Order Value:", round(avg_order_value, 2))

Revenue: 12642905
Profit: 1467457.29
Orders: 25035
Customers: 4873
Average Order Value: 505.01

In [ ]:
category_sales = df.groupby('Category')['Sales'].sum().sort_values(ascending=False)
category_profit = df.groupby('Category')['Profit'].sum().sort_values(ascending=False)
category_orders = df.groupby('Category')['Order ID'].nunique().sort_values(ascending=False)

print("Sales by Category:")
print(category_sales)
print("\n Profit by Category:")
print(category_profit)
print("\n Orders by Category:")
print(category_orders)

Sales by Category:
Category
Technology         4744691
Furniture          4110884
Office Supplies    3787330
Name: Sales, dtype: int64

 Profit by Category:
Category
Technology         663778.73318
Office Supplies    518473.83430
Furniture          285204.72380
Name: Profit, dtype: float64

 Orders by Category:
Category
Office Supplies    19003
Technology          8354
Furniture           8195
Name: Order ID, dtype: int64

In [ ]:
margin = profit/revenue
print(round(margin * 100,1))
# Маржинальность составляет 11.6%, бизнес работает с положительной прибылью, главный показатель выручки - Technology

11.6

In [ ]:
category_margin = (df.groupby("Category").agg({"Sales": "sum","Profit": "sum"}))

category_margin["Margin %"] = (category_margin["Profit"] /category_margin["Sales"] * 100)

print(category_margin)

                   Sales        Profit   Margin %
Category
Furniture        4110884  285204.72380   6.937795
Office Supplies  3787330  518473.83430  13.689693
Technology       4744691  663778.73318  13.989925

In [ ]:
country_sales = (df.groupby("Country").agg({"Sales": "sum","Profit": "sum"}).sort_values("Sales", ascending=False))

print(country_sales.head(10))

                  Sales        Profit
Country
United States   2297354  286397.02170
Australia        925257  103907.43300
France           858930  109029.00300
China            700591  150683.08500
Germany          628857  107322.82050
Mexico           622620  102818.09752
India            589664  129071.83500
United Kingdom   528570  111900.15000
Indonesia        404887   15608.67790
Brazil           361098   30090.49896

In [ ]:
country_profit = (df.groupby("Country")["Profit"].sum().sort_values(ascending=False))

print(country_profit.head(10))

Country
United States     286397.02170
China             150683.08500
India             129071.83500
United Kingdom    111900.15000
France            109029.00300
Germany           107322.82050
Australia         103907.43300
Mexico            102818.09752
Spain              54390.12000
El Salvador        42023.24320
Name: Profit, dtype: float64

In [ ]:
technology_discount = (df[df["Category"] == "Technology"]["Discount"].mean())
ofice_discount = (df[df["Category"] == "Office Supplies"]["Discount"].mean())
furniture_discount = (df[df["Category"] == "Furniture"]["Discount"].mean())

print(ofice_discount)
print(furniture_discount)

print(technology_discount)

0.13740894701499698
0.16808728230052655
0.13534247115669065

In [ ]:
technology_shipping = (df[df["Category"] == "Technology"]["Ship Mode"].value_counts())
ofice_shipping = (df[df["Category"] == "Office Supplies"]["Ship Mode"].value_counts())
furniture_shipping = (df[df["Category"] == "Furniture"]["Ship Mode"].value_counts())
print(technology_shipping)
print(ofice_shipping)
print(furniture_shipping)

Ship Mode
Standard Class    6117
Second Class      2030
First Class       1476
Same Day           518
Name: count, dtype: int64
Ship Mode
Standard Class    18689
Second Class       6311
First Class        4598
Same Day           1675
Name: count, dtype: int64
Ship Mode
Standard Class    5969
Second Class      1968
First Class       1431
Same Day           508
Name: count, dtype: int64

In [ ]:
technology_shipping_cost = (df[df["Category"] == "Technology"]["Shipping Cost"].mean())
ofice_shipping_cost = (df[df["Category"] == "Office Supplies"]["Shipping Cost"].mean())
furniture_shipping_cost = (df[df["Category"] == "Furniture"]["Shipping Cost"].mean())

print('technology_shipping_cost',technology_shipping_cost)
print('\n ofice_shipping_cost',ofice_shipping_cost)
print('\n furniture_shipping_cost',furniture_shipping_cost)

technology_shipping_cost 49.99979088847253

 ofice_shipping_cost 12.96480494356154

 furniture_shipping_cost 44.5847994127177

In [ ]:
df.groupby("Category")[["Discount", "Shipping Cost", "Quantity", "Profit"]].mean()

                 Discount  Shipping Cost  Quantity     Profit
Category
Furniture        0.168087      44.584799  3.539287  28.878567
Office Supplies  0.137409      12.964805  3.459278  16.578961
Technology       0.135342      49.999791  3.468691  65.454958

In [ ]:
df[["Discount", "Shipping Cost", "Profit", "Sales"]].corr()

               Discount  Shipping Cost    Profit     Sales
Discount       1.000000      -0.079055 -0.316490 -0.086728
Shipping Cost -0.079055       1.000000  0.354441  0.768075
Profit        -0.316490       0.354441  1.000000  0.484923
Sales         -0.086728       0.768075  0.484923  1.000000

In [ ]:
df.groupby("Sub-Category").agg({
    "Sales": "sum",
    "Profit": "sum"
}).sort_values("Profit", ascending=False)

                Sales        Profit
Sub-Category
Copiers       1509439  258567.54818
Phones        1706874  216717.00580
Bookcases     1466559  161924.41950
Appliances    1011081  141680.58940
Chairs        1501682  140396.26750
Accessories    749307  129626.30620
Storage       1127124  108461.48980
Binders        461952   72449.84600
Paper          244307   59207.68270
Machines       779071   58867.87300
Art            372163   57953.91090
Furnishings    385609   46967.42550
Envelopes      170926   29601.11630
Supplies       243090   22583.26310
Labels          73433   15010.51200
Fasteners       83254   11525.42410
Tables         757034  -64083.38870

In [ ]:
df.groupby("Sub-Category").agg({
    "Discount": "mean",
    "Shipping Cost": "mean"
})

              Discount  Shipping Cost
Sub-Category
Accessories   0.120481      27.158808
Appliances    0.141709      61.709736
Art           0.117362       8.455282
Binders       0.179207       7.831878
Bookcases     0.153758      64.488580
Chairs        0.163110      47.824506
Copiers       0.117147      71.748180
Envelopes     0.131749       7.617038
Fasteners     0.140595       3.741049
Furnishings   0.151066      12.853869
Labels        0.120449       3.092738
Machines      0.169583      53.254272
Paper         0.109469       7.535570
Phones        0.145847      55.079682
Storage       0.138464      23.828036
Supplies      0.127918      10.231558
Tables        0.290732      92.754232

In [ ]:
furniture_sub_category_sales = df[df['Category'] == 'Furniture'].groupby('Sub-Category')['Sales'].sum().sort_values(ascending=False)
print("Sales by Sub-Category within Furniture:")
print(furniture_sub_category_sales)

Sales by Sub-Category within Furniture:
Sub-Category
Chairs         1501682
Bookcases      1466559
Tables          757034
Furnishings     385609
Name: Sales, dtype: int64